services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    container_name: loki
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=minmin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:465
      - GF_SMTP_USER=ittracer2018@gmail.com
      - GF_SMTP_PASSWORD=ynot ummf onnk njov
    volumes:
      - grafana-data:/var/lib/grafana
    container_name: grafana
volumes:
  loki-data:
  grafana-data:
  

 